/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Principal;
import Model.PaisOlimpico;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author CarlosHVChaves
 */
public class GraphicOlimpicoDeDesempenhoUmPais extends javax.swing.JFrame {

    /**
     * Creates new form GraphicOlimpico1
     */
    public GraphicOlimpicoDeDesempenhoUmPais() {
        initComponents();
        //init();
        preencheComboBox();
    }

    private void preencheComboBox() {
        cbPais.removeAllItems();
        ArrayList<PaisOlimpico> paisOlimpico = Principal.getPaisesOlimpicos();
        for (PaisOlimpico c : paisOlimpico) {
            cbPais.addItem(c.getNome());
        }
    }

        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpGraphic = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        cbPais = new javax.swing.JComboBox<>();
        btnGerarGrafico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 583));

        jpGraphic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpGraphic.setLayout(new java.awt.BorderLayout());

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        cbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um pais" }));

        btnGerarGrafico.setText("Gerar Gráfico");
        btnGerarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarGraficoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpGraphic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(btnGerarGrafico)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar)
                        .addGap(0, 408, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpGraphic, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerarGrafico))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnGerarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarGraficoActionPerformed
        int pos1 = cbPais.getSelectedIndex();


        PaisOlimpico paisOlimpico = Principal.getPaisesOlimpicos().get(pos1);
        int[] medalhasDeCadaAno = paisOlimpico.pegaDadosCadaAno();

        // cria o conjunto de dados
        DefaultCategoryDataset ds = new DefaultCategoryDataset();
        for(int cont = 0; cont < medalhasDeCadaAno.length; cont++){
            ds.addValue(medalhasDeCadaAno[cont], "", (paisOlimpico.getAnosOlimpicos().get(cont).getAno())+"");
        }
                   

        // cria o gráfico
        //JFreeChart grafico = ChartFactory.create("Desempenho de todas Olímpiadas", "Total", "Todas as medalhas até agora", ds, PlotOrientation.HORIZONTAL, false, false, false);
        JFreeChart grafico = ChartFactory.createAreaChart("Desempenho de cada país", "Anos", "Desempenho por ano", ds, PlotOrientation.VERTICAL, false, false, false);
        CategoryPlot plot = grafico.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.BLACK);

        ChartPanel chartPanel = new ChartPanel(grafico);
        jpGraphic.removeAll();
        jpGraphic.add(chartPanel, BorderLayout.CENTER);
        jpGraphic.validate();
    }//GEN-LAST:event_btnGerarGraficoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicOlimpicoDeDesempenhoUmPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicOlimpicoDeDesempenhoUmPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicOlimpicoDeDesempenhoUmPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicOlimpicoDeDesempenhoUmPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicOlimpicoDeDesempenhoUmPais().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarGrafico;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbPais;
    private javax.swing.JPanel jpGraphic;
    // End of variables declaration//GEN-END:variables
}
