/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Principal;
import Model.PaisOlimpico;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CarlosHVChaves
 */
public class MedidasCentral extends javax.swing.JFrame {

    /**
     * Creates new form MedidasCentral
     */
    public MedidasCentral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "País", "Medalhas", "Média", "Moda", "Mediana"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table1);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedidasCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedidasCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedidasCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedidasCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedidasCentral().setVisible(true);
            }
        });
    }
    
    /*public void PreencherPais(ArrayList<PaisOlimpico> ps){
        for (PaisOlimpico p : ps) {
            if (p instanceof PaisOlimpico) {
                boxPaises.addItem(p.getNome());
            }
        }
    }*/
    
    public void aplicaTable() throws SQLException {//pega os parametros de filtro, chama o DAO e chama o mostraPesquisa

        /*String id = (String) buscId.getText();
        String nome = (String) buscNome.getText();
        String cpf = (String) buscCpf.getText();
        String bairro = (String) buscBairro.getText();*/

        /*ClienteDAO dao = new ClienteDAO();*/
        List<PaisOlimpico> titulob = Principal.getPaisesOlimpicos();
        mostraPesquisa(titulob);
    }

    private void mostraPesquisa(List<PaisOlimpico> titulob) {//pega uma lista e coloca na table
        while (table1.getRowCount() > 0) {
            // Mostra a pesquisa
            ((DefaultTableModel) table1.getModel()).removeRow(0);
        }
        if (titulob.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum país encontrado");
        } else {
            //TableColumn openColumn = tbClientes.getColumnModel().getColumn(0);
            String[] linha = new String[]{null, null, null,null};
            //int j = titulob.size()-1;
            for (int i = 0; i < titulob.size(); i++) {
                
                ((DefaultTableModel) table1.getModel()).addRow(linha);

                //openColumn.setCellEditor(new DefaultCellEditor(b));
                table1.setValueAt(titulob.get(i).getNome(), i, 0);
                table1.setValueAt(titulob.get(i).totalMedalhas(), i, 1);
                table1.setValueAt(titulob.get(i).mediaMedalhas(), i, 2);
                table1.setValueAt(titulob.get(i).modaMedalhas(), i, 3);
                table1.setValueAt(titulob.get(i).medianaMedalhas(), i, 4);
                //j--;
            }
            table1.getColumnModel().getColumn(0).setMinWidth(170);//essas linhas limitam a largura da coluna
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
