/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Principal;
import Model.PaisOlimpico;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CarlosHVChaves
 */
public class MedidasDispersao extends javax.swing.JFrame {

    /**
     * Creates new form MedidasDispersao
     */
    public MedidasDispersao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "País", "Medalhas", "Desvio Médio", "Variância", "Desvio Padrão", "Coeficiente de Variação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table2);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(814, 814, 814)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedidasDispersao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedidasDispersao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedidasDispersao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedidasDispersao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedidasDispersao().setVisible(true);
            }
        });
    }
    
    /*public void PreencherPais(ArrayList<PaisOlimpico> ps){
        for (PaisOlimpico p : ps) {
            if (p instanceof PaisOlimpico) {
                boxPaises.addItem(p.getNome());
            }
        }
    }*/
    
    public void aplicaTable() throws SQLException {//pega os parametros de filtro, chama o DAO e chama o mostraPesquisa

        /*String id = (String) buscId.getText();
        String nome = (String) buscNome.getText();
        String cpf = (String) buscCpf.getText();
        String bairro = (String) buscBairro.getText();*/

        /*ClienteDAO dao = new ClienteDAO();*/
        List<PaisOlimpico> titulob = Principal.getPaisesOlimpicos();
        mostraPesquisa(titulob);
    }

    private void mostraPesquisa(List<PaisOlimpico> titulob) {//pega uma lista e coloca na table
        while (table2.getRowCount() > 0) {
            // Mostra a pesquisa
            ((DefaultTableModel) table2.getModel()).removeRow(0);
        }
        if (titulob.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum país encontrado");
        } else {
            //TableColumn openColumn = tbClientes.getColumnModel().getColumn(0);
            String[] linha = new String[]{null, null, null,null};
            //int j = titulob.size()-1;
            for (int i = 0; i < titulob.size(); i++) {
                
                ((DefaultTableModel) table2.getModel()).addRow(linha);

                //openColumn.setCellEditor(new DefaultCellEditor(b));
                table2.setValueAt(titulob.get(i).getNome(), i, 0);
                table2.setValueAt(titulob.get(i).totalMedalhas(), i, 1);
                table2.setValueAt(titulob.get(i).desvioMedio(), i, 2);
                table2.setValueAt(titulob.get(i).variancia(), i, 3);
                table2.setValueAt(titulob.get(i).desvioPadrão(), i, 4);
                table2.setValueAt(titulob.get(i).coeficienteDeVariacao(), i, 5);
                //j--;
            }
            table2.getColumnModel().getColumn(0).setMinWidth(170);//essas linhas limitam a largura da coluna
            //table2.getColumnModel().getColumn(1).setMaxWidth(60);
            //table2.getColumnModel().getColumn(3).setMaxWidth(80);
            //table2.getColumnModel().getColumn(4).setMinWidth(140);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
